
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback lets `prisma generate` run in clean-room builds (Docker builder
    // has no secrets — correctly). Anything touching a real DB (migrate
    // deploy, the app) gets the real URL from runtime env and never sees this.
    url: process.env.DATABASE_URL ?? "postgresql://build:build@localhost:5432/build?schema=public",
  },
});
